version: "3.8"

services:
  filebrowser:
    build:
      context: .
      dockerfile: _docker/Dockerfile
    container_name: filebrowser_osdosintegrated
    user: "0:0"
    ports:
      # Use the variable from the .env file
      - "${FILEBROWSER_PORT}:80"
    volumes:
      # Use variables for the host paths
      - ${MAIN_IMAGE_PATH}:/srv
      - ${ALT_IMAGE_PATH}:/srv/old-images
      - ./config:/config
      - ./database:/database
    environment:
      FILEBROWSER_CONFIG: "/config/config.yaml"
      # The application reads this environment variable at startup
      FILEBROWSER_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    restart: unless-stopped

  slideserver:
    build:
      context: ./slideserver
    container_name: slideserver_integrated
    volumes:
      # Use variables for the host paths
      - ${MAIN_IMAGE_PATH}:/srv:ro
      - ${ALT_IMAGE_PATH}:/srv/old-images:ro
      # Use the named volume defined below
      - ${WSI_CACHE_VOLUME}:/cache
    restart: unless-stopped

# Define the named volume using the variable from the .env file
# volumes:
#   ${WSI_CACHE_VOLUME}: